theme: minima
title: Just a title.
author: 13thHKG
email: sanzharthenexthokage@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a description for my new site about nothing.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
